version: "3.8"

volumes:
  postgres_data:

services:
  deno-app:
    container_name: deno-app
    build: ./deno-app/
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    deploy:
      # configures physical resource constraints for container to run on platform
      resources:
        # The platform must prevent the container to allocate more.
        limits:
          # configures a limit or reservation for how much of the available CPU resources, as number of cores, a container can use.
          cpus: "1.0"
          # configures a limit or reservation on the amount of memory a container can allocate
          memory: "256M"
        # The platform must guarantee the container can allocate at least the configured amount.
        reservations:
          cpus: "0.5"
          memory: "128M"

  express-app:
    container_name: express-app
    build: ./express-app/
    ports:
      - "7070:7070"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "256M"
        reservations:
          cpus: "0.5"
          memory: "128M"
  postgres:
    image: postgres:17.2
    container_name: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    # command:
    #   - "postgres"
    #   - "-c"
    #   - "max_connections=50"
    #   - "-c"
    #   - "shared_buffers=1GB"
    #   - "-c"
    #   - "effective_cache_size=4GB"
    #   - "-c"
    #   - "work_mem=16MB"
    #   - "-c"
    #   - "maintenance_work_mem=512MB"
    #   - "-c"
    #   - "random_page_cost=1.1"
    #   - "-c"
    #   - "temp_file_limit=10GB"
    #   - "-c"
    #   - "log_min_duration_statement=200ms"
    #   - "-c"
    #   - "idle_in_transaction_session_timeout=10s"
    #   - "-c"
    #   - "lock_timeout=1s"
    #   - "-c"
    #   - "statement_timeout=60s"
    #   - "-c"
    #   - "shared_preload_libraries=pg_stat_statements"
    #   - "-c"
    #   - "pg_stat_statements.max=10000"
    #   - "-c"
    #   - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1946alien" # or 1946alien
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 10G
